version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - FACEBOOK_LEADS_DIR=/app/Database/leads_facebook
      - PITCHYES_CALLS_DIR=/app/Database/chamadas_pitchyes
      - SCRIPT_PATH=/app/Database/build_database.py
    volumes:
      - ./Database:/app/Database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

